# This file has been generated by node2nix 1.5.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "archiver-1.3.0" = {
      name = "archiver";
      packageName = "archiver";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archiver/-/archiver-1.3.0.tgz";
        sha1 = "4f2194d6d8f99df3f531e6881f14f15d55faaf22";
      };
    };
    "archiver-utils-1.3.0" = {
      name = "archiver-utils";
      packageName = "archiver-utils";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archiver-utils/-/archiver-utils-1.3.0.tgz";
        sha1 = "e50b4c09c70bf3d680e32ff1b7994e9f9d895174";
      };
    };
    "argparse-1.0.9" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.9.tgz";
        sha1 = "73d83bc263f86e97f8cc4f6bae1b0e90a7d22c86";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-1.4.1" = {
      name = "assert";
      packageName = "assert";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.4.1.tgz";
        sha1 = "99912d591836b5a6f5b345c0f07eefc08fc65d91";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-0.9.2" = {
      name = "async";
      packageName = "async";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.9.2.tgz";
        sha1 = "aea74d5e61c1f899613bf64bda66d4c78f2fd17d";
      };
    };
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "async-2.6.0" = {
      name = "async";
      packageName = "async";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.0.tgz";
        sha512 = "0zp4b5788400npi1ixjry5x3a4m21c8pnknk8v731rgnwnjbp5ijmfcf5ppmn1ap4a04md1s9dr8n9ygdvrmiai590v0k6dby1wc1y4";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "bl-1.2.1" = {
      name = "bl";
      packageName = "bl";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.2.1.tgz";
        sha1 = "cac328f7bee45730d404b692203fcb590e172d5e";
      };
    };
    "boom-4.3.1" = {
      name = "boom";
      packageName = "boom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-4.3.1.tgz";
        sha1 = "4f8a3005cb4a7e3889f749030fd25b96e01d2e31";
      };
    };
    "boom-5.2.0" = {
      name = "boom";
      packageName = "boom";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-5.2.0.tgz";
        sha512 = "19h20yqpvca08dns1rs4f057f10w63v0snxfml4h5khsk266x3x1im0w72bza4k2xn0kfz6jlv001dhcvxsjr09bmbqnysils9m7437";
      };
    };
    "brace-expansion-1.1.8" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz";
        sha1 = "c07b211c7c952ec1f8efd51a77ef0d1d3990a292";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha1 = "0d333e3f00eac50aa1454abd30ef8c2a5d9a7242";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "colors-1.1.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz";
        sha1 = "168a4701756b6a7f51a12ce0c97bfa28c084ed63";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "compress-commons-1.2.2" = {
      name = "compress-commons";
      packageName = "compress-commons";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/compress-commons/-/compress-commons-1.2.2.tgz";
        sha1 = "524a9f10903f3a813389b0225d27c48bb751890f";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "crc-3.5.0" = {
      name = "crc";
      packageName = "crc";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc/-/crc-3.5.0.tgz";
        sha1 = "98b8ba7d489665ba3979f59b21381374101a1964";
      };
    };
    "crc32-stream-2.0.0" = {
      name = "crc32-stream";
      packageName = "crc32-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc32-stream/-/crc32-stream-2.0.0.tgz";
        sha1 = "e3cdd3b4df3168dd74e3de3fbbcb7b297fe908f4";
      };
    };
    "cryptiles-3.1.2" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-3.1.2.tgz";
        sha1 = "a89fbb220f5ce25ec56e8c4aa8a4fd7b5b0d29fe";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "deep-equal-0.2.2" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-0.2.2.tgz";
        sha1 = "84b745896f34c684e98f2ce0e42abaf43bba017d";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "end-of-stream-1.4.1" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.1.tgz";
        sha512 = "3cjrpi6n5i6gf8jaiwg31y2xkgx59szhhcj9myqwmdw16s9r6yvwznxd2lhqf96mpm6knyb3w2bcnksg5nzkrq6iada0k6nvdj2pjfl";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "fast-deep-equal-1.0.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.0.0.tgz";
        sha1 = "96256a3bc975595eb36d82e9929d060d893439ff";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.1.tgz";
        sha1 = "6fb94fbd71885306d73d15cc497fe4cc4ecd44bf";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.0.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz";
        sha1 = "ba402c266194f15956ef15e0fcf242993f6a7dfd";
      };
    };
    "hawk-6.0.2" = {
      name = "hawk";
      packageName = "hawk";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-6.0.2.tgz";
        sha512 = "1nl2hjr2mnhj5jlaz8mh54z7acwz5j5idkch04qgjk78756gw5d0fjk4a2immil5ij9ijdssb9ndpryvnh2xpcbgcjv8lxybn330als";
      };
    };
    "hoek-4.2.0" = {
      name = "hoek";
      packageName = "hoek";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-4.2.0.tgz";
        sha512 = "2cz0q3nnv67drgaw2rm7q57r9rgdax1qa0n4z46is7db1w8vwmh574xcr0d73xl5lg80vb85xg2gdhxzh9gbllagp7xk2q228pw4idz";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "i-0.3.6" = {
      name = "i";
      packageName = "i";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/i/-/i-0.3.6.tgz";
        sha1 = "d96c92732076f072711b6b10fd7d4f65ad8ee23d";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "lazystream-1.0.0" = {
      name = "lazystream";
      packageName = "lazystream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazystream/-/lazystream-1.0.0.tgz";
        sha1 = "f6995fe0f820392f61396be89462407bb77168e4";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "mute-stream-0.0.7" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.7.tgz";
        sha1 = "3075ce93bc21b8fab43e1bc4da7e8115ed1e7bab";
      };
    };
    "ncp-1.0.1" = {
      name = "ncp";
      packageName = "ncp";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncp/-/ncp-1.0.1.tgz";
        sha1 = "d15367e5cb87432ba117d2bf80fdf45aecfb4246";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha1 = "1ab28b556e198363a8c1a6f7e6fa20137fe6aed9";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "pkginfo-0.3.1" = {
      name = "pkginfo";
      packageName = "pkginfo";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.1.tgz";
        sha1 = "5b29f6a81f70717142e09e765bbeab97b4f81e21";
      };
    };
    "pkginfo-0.4.1" = {
      name = "pkginfo";
      packageName = "pkginfo";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkginfo/-/pkginfo-0.4.1.tgz";
        sha1 = "b5418ef0439de5425fc4995042dced14fb2a84ff";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "prompt-1.0.0" = {
      name = "prompt";
      packageName = "prompt";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prompt/-/prompt-1.0.0.tgz";
        sha1 = "8e57123c396ab988897fb327fd3aedc3e735e4fe";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-6.5.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.1.tgz";
        sha512 = "3waqapyj1k4g135sgj636rmswiaixq19is1rw0rpv4qp6k7dl0a9nwy06m7yl5lbdk9p6xpwwngnggbzlzaz6rh11c86j2nvnnf273r";
      };
    };
    "read-1.0.7" = {
      name = "read";
      packageName = "read";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/read/-/read-1.0.7.tgz";
        sha1 = "b3da19bd052431a97671d44a42634adf710b40c4";
      };
    };
    "readable-stream-2.3.3" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.3.tgz";
        sha512 = "1wlizkv2wnz2nyb0lfxgs1m27zzcvasp3n5cfrd7hm4ch1wn79df2nbhzfadba5qqdfb28vhmw3drhp46vk2q6xk524qagvr76v7slv";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "request-2.83.0" = {
      name = "request";
      packageName = "request";
      version = "2.83.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.83.0.tgz";
        sha512 = "0by1djkn836sqd9pk2c777wcjvp34qbk1plx7s4lmykljrblpjc64dvn6ni2vyxsbyk33wnl6avym8vgw0ggr4226xakck8mw7y07cm";
      };
    };
    "revalidator-0.1.8" = {
      name = "revalidator";
      packageName = "revalidator";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/revalidator/-/revalidator-0.1.8.tgz";
        sha1 = "fece61bfa0c1b52a206bd6b18198184bdd523a3b";
      };
    };
    "rimraf-2.6.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.2.tgz";
        sha512 = "3kmrqh8xli7rzfm8wc6j9lp0c6vml172iv3z088an9xlwl1xvkvh3fn92za66ms4c9yww80qa5kan31k1z1ypqvkchmh1mznb09xdwn";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "sntp-2.1.0" = {
      name = "sntp";
      packageName = "sntp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-2.1.0.tgz";
        sha512 = "0k2smmr24w5hb1cpql6vcgh58vzp4pmh9anf0bgz3arlsgq1mapnlq9fjqr6xs10aq1cmxaw987fwknqi62frax0fvs9bj3q3kmpg8l";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "sshpk-1.13.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz";
        sha1 = "512df6da6287144316dc4c18fe1cf1d940739be3";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "string_decoder-1.0.3" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz";
        sha512 = "22vw5mmwlyblqc2zyqwl39wyhyahhpiyknim8iz5fk6xi002x777gkswiq8fh297djs5ii4pgrys57wq33hr5zf3xfd0d7kjxkzl0g0";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tar-stream-1.5.5" = {
      name = "tar-stream";
      packageName = "tar-stream";
      version = "1.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-stream/-/tar-stream-1.5.5.tgz";
        sha512 = "219gn10gvilrq6h3yshbhn25fx46n0wlgg66h0v326jhzz8gmpxsinb8bnhx1py35z0cv2248v91k2vy6vmkajmvpmkfmizywn601wr";
      };
    };
    "tough-cookie-2.3.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.3.tgz";
        sha1 = "0b618a5565b6dea90bf3425d04d55edc475a7561";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "utile-0.3.0" = {
      name = "utile";
      packageName = "utile";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utile/-/utile-0.3.0.tgz";
        sha1 = "1352c340eb820e4d8ddba039a4fbfaa32ed4ef3a";
      };
    };
    "uuid-3.2.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz";
        sha512 = "0843vl1c974n8kw5kn0kvhvhwk8y8jydr0xkwwl2963xxmkw4ingk6xj9c8m48jw2i95giglxzq5aw5v5mij9kv7fzln8pxav1cr6cd";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "walkdir-0.0.11" = {
      name = "walkdir";
      packageName = "walkdir";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/walkdir/-/walkdir-0.0.11.tgz";
        sha1 = "a16d025eb931bd03b52f308caed0f40fcebe9532";
      };
    };
    "winston-2.1.1" = {
      name = "winston";
      packageName = "winston";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.1.1.tgz";
        sha1 = "3c9349d196207fd1bdff9d4bc43ef72510e3a12e";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "zip-stream-1.2.0" = {
      name = "zip-stream";
      packageName = "zip-stream";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/zip-stream/-/zip-stream-1.2.0.tgz";
        sha1 = "a8bc45f4c1b49699c6b90198baacaacdbcd4ba04";
      };
    };
  };
  args = {
    name = "plonetheme-upload";
    packageName = "plonetheme-upload";
    version = "0.9.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/plonetheme-upload/-/plonetheme-upload-0.9.3.tgz";
      sha256 = "443279f75870665a4a680039a5e6f82cb8678f2defb505a22a0f8bbdf059eb1a";
    };
    dependencies = [
      (sources."archiver-1.3.0" // {
        dependencies = [
          (sources."archiver-utils-1.3.0" // {
            dependencies = [
              sources."graceful-fs-4.1.11"
              sources."lazystream-1.0.0"
              (sources."normalize-path-2.1.1" // {
                dependencies = [
                  sources."remove-trailing-separator-1.1.0"
                ];
              })
            ];
          })
          sources."async-2.6.0"
          sources."buffer-crc32-0.2.13"
          (sources."glob-7.1.2" // {
            dependencies = [
              sources."fs.realpath-1.0.0"
              (sources."inflight-1.0.6" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."inherits-2.0.3"
              (sources."minimatch-3.0.4" // {
                dependencies = [
                  (sources."brace-expansion-1.1.8" // {
                    dependencies = [
                      sources."balanced-match-1.0.0"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."once-1.4.0" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."path-is-absolute-1.0.1"
            ];
          })
          sources."lodash-4.17.4"
          (sources."readable-stream-2.3.3" // {
            dependencies = [
              sources."core-util-is-1.0.2"
              sources."inherits-2.0.3"
              sources."isarray-1.0.0"
              sources."process-nextick-args-1.0.7"
              sources."safe-buffer-5.1.1"
              sources."string_decoder-1.0.3"
              sources."util-deprecate-1.0.2"
            ];
          })
          (sources."tar-stream-1.5.5" // {
            dependencies = [
              sources."bl-1.2.1"
              (sources."end-of-stream-1.4.1" // {
                dependencies = [
                  (sources."once-1.4.0" // {
                    dependencies = [
                      sources."wrappy-1.0.2"
                    ];
                  })
                ];
              })
              sources."xtend-4.0.1"
            ];
          })
          sources."walkdir-0.0.11"
          (sources."zip-stream-1.2.0" // {
            dependencies = [
              (sources."compress-commons-1.2.2" // {
                dependencies = [
                  (sources."crc32-stream-2.0.0" // {
                    dependencies = [
                      sources."crc-3.5.0"
                    ];
                  })
                  (sources."normalize-path-2.1.1" // {
                    dependencies = [
                      sources."remove-trailing-separator-1.1.0"
                    ];
                  })
                ];
              })
            ];
          })
        ];
      })
      (sources."argparse-1.0.9" // {
        dependencies = [
          sources."sprintf-js-1.0.3"
        ];
      })
      (sources."assert-1.4.1" // {
        dependencies = [
          (sources."util-0.10.3" // {
            dependencies = [
              sources."inherits-2.0.1"
            ];
          })
        ];
      })
      (sources."prompt-1.0.0" // {
        dependencies = [
          sources."colors-1.1.2"
          sources."pkginfo-0.4.1"
          (sources."read-1.0.7" // {
            dependencies = [
              sources."mute-stream-0.0.7"
            ];
          })
          sources."revalidator-0.1.8"
          (sources."utile-0.3.0" // {
            dependencies = [
              sources."async-0.9.2"
              sources."deep-equal-0.2.2"
              sources."i-0.3.6"
              (sources."mkdirp-0.5.1" // {
                dependencies = [
                  sources."minimist-0.0.8"
                ];
              })
              sources."ncp-1.0.1"
              (sources."rimraf-2.6.2" // {
                dependencies = [
                  (sources."glob-7.1.2" // {
                    dependencies = [
                      sources."fs.realpath-1.0.0"
                      (sources."inflight-1.0.6" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      sources."inherits-2.0.3"
                      (sources."minimatch-3.0.4" // {
                        dependencies = [
                          (sources."brace-expansion-1.1.8" // {
                            dependencies = [
                              sources."balanced-match-1.0.0"
                              sources."concat-map-0.0.1"
                            ];
                          })
                        ];
                      })
                      (sources."once-1.4.0" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      sources."path-is-absolute-1.0.1"
                    ];
                  })
                ];
              })
            ];
          })
          (sources."winston-2.1.1" // {
            dependencies = [
              sources."async-1.0.0"
              sources."colors-1.0.3"
              sources."cycle-1.0.3"
              sources."eyes-0.1.8"
              sources."isstream-0.1.2"
              sources."pkginfo-0.3.1"
              sources."stack-trace-0.0.10"
            ];
          })
        ];
      })
      (sources."request-2.83.0" // {
        dependencies = [
          sources."aws-sign2-0.7.0"
          sources."aws4-1.6.0"
          sources."caseless-0.12.0"
          (sources."combined-stream-1.0.5" // {
            dependencies = [
              sources."delayed-stream-1.0.0"
            ];
          })
          sources."extend-3.0.1"
          sources."forever-agent-0.6.1"
          (sources."form-data-2.3.1" // {
            dependencies = [
              sources."asynckit-0.4.0"
            ];
          })
          (sources."har-validator-5.0.3" // {
            dependencies = [
              (sources."ajv-5.5.2" // {
                dependencies = [
                  sources."co-4.6.0"
                  sources."fast-deep-equal-1.0.0"
                  sources."fast-json-stable-stringify-2.0.0"
                  sources."json-schema-traverse-0.3.1"
                ];
              })
              sources."har-schema-2.0.0"
            ];
          })
          (sources."hawk-6.0.2" // {
            dependencies = [
              sources."boom-4.3.1"
              (sources."cryptiles-3.1.2" // {
                dependencies = [
                  sources."boom-5.2.0"
                ];
              })
              sources."hoek-4.2.0"
              sources."sntp-2.1.0"
            ];
          })
          (sources."http-signature-1.2.0" // {
            dependencies = [
              sources."assert-plus-1.0.0"
              (sources."jsprim-1.4.1" // {
                dependencies = [
                  sources."extsprintf-1.3.0"
                  sources."json-schema-0.2.3"
                  (sources."verror-1.10.0" // {
                    dependencies = [
                      sources."core-util-is-1.0.2"
                    ];
                  })
                ];
              })
              (sources."sshpk-1.13.1" // {
                dependencies = [
                  sources."asn1-0.2.3"
                  sources."bcrypt-pbkdf-1.0.1"
                  sources."dashdash-1.14.1"
                  sources."ecc-jsbn-0.1.1"
                  sources."getpass-0.1.7"
                  sources."jsbn-0.1.1"
                  sources."tweetnacl-0.14.5"
                ];
              })
            ];
          })
          sources."is-typedarray-1.0.0"
          sources."isstream-0.1.2"
          sources."json-stringify-safe-5.0.1"
          (sources."mime-types-2.1.17" // {
            dependencies = [
              sources."mime-db-1.30.0"
            ];
          })
          sources."oauth-sign-0.8.2"
          sources."performance-now-2.1.0"
          sources."qs-6.5.1"
          sources."safe-buffer-5.1.1"
          sources."stringstream-0.0.5"
          (sources."tough-cookie-2.3.3" // {
            dependencies = [
              sources."punycode-1.4.1"
            ];
          })
          sources."tunnel-agent-0.6.0"
          sources."uuid-3.2.1"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Tool for zipping and uploading a Plone theme over HTTP";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
