#!/usr/bin/env bash
# afew -C $prefix/.notmuch-jyu --move-mails --all
mbsync --push --pull --create --new --delete --flags --renew \
       --expunge-slave jyu
# mbsync --push --pull --create --new --delete --flags --renew \
#        --expunge-slave --expunge-master jyu
