#!/usr/bin/env bash
# afew -C $prefix/.notmuch-jyu --tag -- folder:INBOX
# afew -C $prefix/.notmuch-jyu --tag --new
alot -n $prefix/.notmuch-jyu
# afew -C $prefix/.notmuch-jyu --tag --all
# afew -C $prefix/.notmuch-jyu --learn tag -- folder:
# afew -C $prefix/.notmuch-jyu --learn tag -- from:
# afew -C $prefix/.notmuch-jyu --learn tag -- to:
# afew -C $prefix/.notmuch-jyu --update
# afew -C $prefix/.notmuch-jyu --update-reference
