#!/usr/bin/env bash
afew -C $prefix/.notmuch-iki --tag -- folder:INBOX
afew -C $prefix/.notmuch-iki --tag --new
alot -n $prefix/.notmuch-iki
# afew -C $prefix/.notmuch-iki --tag --all
# afew -C $prefix/.notmuch-iki --learn tag -- folder:
# afew -C $prefix/.notmuch-iki --learn tag -- from:
# afew -C $prefix/.notmuch-iki --learn tag -- to:
# afew -C $prefix/.notmuch-iki --update
# afew -C $prefix/.notmuch-iki --update-reference
