#!/usr/bin/env bash
# afew -C $HOME/.notmuch-iki --move-mails --all
mbsync --push --pull --create --new --delete --flags --renew \
       --expunge-slave iki
# mbsync --push --pull --create --new --delete --flags --renew \
#        --expunge-slave --expunge-master iki
