# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Clean tmp on reboot
  boot.cleanTmpDir = true;

  # Minimal list of modules to use the EFI system partition and the YubiKey
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ] ++ [ "vfat" "nls_cp437" "nls_iso8859-1" ];

  # Support LUKS with Yubikey
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.initrd.luks.yubikeySupport = true;

  # Configuration to use your Luks device
  boot.initrd.luks.devices = {
    "nixos-enc" = {
      device = "/dev/nvme0n1p1";
      preLVM = true; # You may want to set this to false if you need to start a network service first
      yubikey = {
        slot = 2;
        twoFactor = false; # Set to false if you did not set up a user password.
        storage = {
          device = "/dev/nvme0n1p2";
        };
      };
      bypassWorkqueues = true;
    }; 
  };

  # Enable scheduled TRIM for SSD
  services.fstrim.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6235c903-8de9-40d0-a252-0cd40de3ea2a";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/03F4-A35A";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/02c9f0d3-5c8e-4933-a383-739099716944"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Networking
  networking.hostName = "desktop";
  networking.hosts = {
    "127.0.1.1" = [ "desktop" ];
    "::1" = [ "localhost" ];
  };

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = false;
  networking.interfaces.eno1.useDHCP = true;

  # Graphics
  hardware.opengl.enable = true;

  # Initial system version
  system.stateVersion = "21.11";
}
