# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "PyYAML" = super.buildPythonPackage rec {
    pname = "PyYAML";
    version = "5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz";
      sha256 = "15czj11s2bcgchn2jx81k0jmswf2hjxry5cq820h7hgpxiscfss3";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "argh" = super.buildPythonPackage rec {
    pname = "argh";
    version = "0.26.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/1c/e667a7126f0b84aaa1c56844337bf0ac12445d1beb9c8a6199a7314944bf/argh-0.26.2-py2.py3-none-any.whl";
      sha256 = "1wyagxyxq6wpb2m8sj6wyr5gph3syg34dkcl4gipissfj2hsmcx9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "asn1crypto" = super.buildPythonPackage rec {
    pname = "asn1crypto";
    version = "0.24.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl";
      sha256 = "11sfqs4zx8v2nmzgn4bxmidmiwswbk4kxwhfr7irklbfajvxn6ig";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.12.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz";
      sha256 = "0x075521fxwv0mfp4cqzk7lvmw4n94bjw601qkcv314z5s182704";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "2.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/ca/bc827c5e55918ad223d59d299fff92f3563476c3b00d0a9157d9c0217449/cryptography-2.6.1.tar.gz";
      sha256 = "19iwz5avym5zl6jrrrkym1rdaa9h61j20ph4cswsqgv8xg5j3j16";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asn1crypto"
      self."cffi"
      self."enum34"
      self."ipaddress"
      self."six"
    ];
  };
  "dataflake-fakeldap" = super.buildPythonPackage rec {
    pname = "dataflake-fakeldap";
    version = "1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/f4/adb8dcb2646fc559c6a78bdd01dd5f7809efee2695871d3c78168f8c328d/dataflake.fakeldap-1.0.tar.gz";
      sha256 = "1ll53h4hdnvac2az0vyh483c8333r6g44sz077ddisrc5wq1y7jj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools-git"
    ];
    propagatedBuildInputs = [
      self."python-ldap"
      self."setuptools"
    ];
  };
  "enum34" = super.buildPythonPackage rec {
    pname = "enum34";
    version = "1.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl";
      sha256 = "0yccrlzc54rxbi7qikag9nlcvv2d906r8hfiscbs2apc92nzdl3b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fancycompleter" = super.buildPythonPackage rec {
    pname = "fancycompleter";
    version = "0.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/e3/da39a6cfaffe578a01221261ac1d5d99c48d44f6377ff0de3a12dd332cec/fancycompleter-0.8.tar.gz";
      sha256 = "04lvacix99d242b1jv2qxdi6gq1djv8w1i3racliydqj6lgjylnj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools-scm"
    ];
    propagatedBuildInputs = [
      self."pyrepl"
    ];
  };
  "gnureadline" = super.buildPythonPackage rec {
    pname = "gnureadline";
    version = "6.3.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/50/64/86085c823cd78f9df9d8e33dce0baa71618016f8860460b82cf6610e1eb3/gnureadline-6.3.8.tar.gz";
      sha256 = "0ddhj98x2nv45iz4aadk4b9m0b1kpsn1xhcbypn5cd556knhiqjq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ipaddress" = super.buildPythonPackage rec {
    pname = "ipaddress";
    version = "1.0.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl";
      sha256 = "1537ggzx7iaiss9nqa2am9f5fp0ah04dmm7nk0353rvqbvn8xck4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "kerberos" = super.buildPythonPackage rec {
    pname = "kerberos";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/34/18/9c86fdfdb27e0f7437b7d5a9e22975dcc382637b2a68baac07843be512fc/kerberos-1.3.0.tar.gz";
      sha256 = "19663qxmma0i8bfbjc2iwy5hgq0g4pfb75r023v5dps68zfvffgh";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/29/174d70f303016c58bd790c6c86e6e86a9d18239fac314d55a9b7be501943/lxml-4.3.3.tar.gz";
      sha256 = "141xvx096bh5xm8mhb4nrycgy1fp12ahnklh6h1a2dcf5xlds0sa";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pathlib" = super.buildPythonPackage rec {
    pname = "pathlib";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz";
      sha256 = "17zajiw4mjbkkv6ahp3xf025qglkj0805m9s41c45zryzj6p2h39";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pathtools" = super.buildPythonPackage rec {
    pname = "pathtools";
    version = "0.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/7f/470d6fcdf23f9f3518f6b0b76be9df16dcc8630ad409947f8be2eb0ed13a/pathtools-0.1.2.tar.gz";
      sha256 = "1h7iam33vwxk8bvslfj4qlsdprdnwf8bvzhqh3jq5frr391cadbw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pdbpp" = super.buildPythonPackage rec {
    pname = "pdbpp";
    version = "0.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/c3/cf957fa98406ef25422b3324dee70b3624dacdd05602201af356234059c4/pdbpp-0.10.0.tar.gz";
      sha256 = "1pf4pcnaa4q40nvww3dyyw9zllm1pnwyspmlcsyr4bgkxh1anzpf";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools-scm"
    ];
    propagatedBuildInputs = [
      self."fancycompleter"
      self."pygments"
      self."wmctrl"
    ];
  };
  "pillow" = super.buildPythonPackage rec {
    pname = "pillow";
    version = "6.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/1a/6b2971adc1bca55b9a53ed1efa372acff7e8b9913982a396f3fa046efaf8/Pillow-6.0.0.tar.gz";
      sha256 = "1dgbhamlr5gxk9avfvmq3ivqqp6w9fpp2grinpbvqb03x4n0m740";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1" = super.buildPythonPackage rec {
    pname = "pyasn1";
    version = "0.4.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl";
      sha256 = "0vicia5ims2zsqc96gkfi15afsvprhwgp7kkwa0br4xfr6l46sys";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1-modules" = super.buildPythonPackage rec {
    pname = "pyasn1-modules";
    version = "0.2.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/91/f0/b03e00ce9fddf4827c42df1c3ce10c74eadebfb706231e8d6d1c356a4062/pyasn1_modules-0.2.5-py2.py3-none-any.whl";
      sha256 = "0g7vph4nkbn1vxpf7r8xapbi03j3f36b3zl3lmyazbi48z4vc2gk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz";
      sha256 = "1cr5dcj9628lkz1qlwq3fv97c25363qppkmcayqvd05dpy573259";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycrypto" = super.buildPythonPackage rec {
    pname = "pycrypto";
    version = "2.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz";
      sha256 = "0g0ayql5b9mkjam8hym6zyg6bv77lbh66rv1fyvgqb17kfc1xkpj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycryptodome" = super.buildPythonPackage rec {
    pname = "pycryptodome";
    version = "3.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c0/1e/5398467ff0fcb39dbb23412c5ea9c9b2db2b659282e49d4073daae952247/pycryptodome-3.8.1.tar.gz";
      sha256 = "1cv1fw5qff2pdvg80llbh51a7hp3mdsqaibzpck7lmvllgj0rbb8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl";
      sha256 = "13c14pqvyiznqcdk8f940dz1sqpj9h6hsliqa5s785m6k79qs8g8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrepl" = super.buildPythonPackage rec {
    pname = "pyrepl";
    version = "0.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/1b/ea40363be0056080454cdbabe880773c3c5bd66d7b13f0c8b8b8c8da1e0c/pyrepl-0.9.0.tar.gz";
      sha256 = "0xd7h7k5cg9gd8nkqdykzkxmfasg8wwxcrmrpdqyh0jm9grp0999";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyscss" = super.buildPythonPackage rec {
    pname = "pyscss";
    version = "1.3.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/7b/c6bfb2515ed08cbfb76b0e72254f24caf76f25676d72024837a85a1e68f5/pyScss-1.3.5.tar.gz";
      sha256 = "1c6dh299lw4mkkp3qczry8yqslknydks19h0y2qnp9i1q8rmr8hl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."enum34"
      self."pathlib"
      self."six"
    ];
  };
  "python-ldap" = super.buildPythonPackage rec {
    pname = "python-ldap";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ea/93/596f875e003c770447f4b99267820a0c769dd2dc3ae3ed19afe460fcbad0/python-ldap-3.2.0.tar.gz";
      sha256 = "13nvrhp85yr0jyxixcjj012iw8l9wynxxlykm9j3alss6waln73x";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
      self."pyasn1-modules"
    ];
  };
  "python-magic" = super.buildPythonPackage rec {
    pname = "python-magic";
    version = "0.4.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl";
      sha256 = "0x8khcb0695rzf695v0xvcqb2h4mh0ks0gw0si4nrbjjmp7lsrzj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "robotframework" = super.buildPythonPackage rec {
    pname = "robotframework";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/c6/6f89c80ac5a526a091bd383ffdfc64c9a68d9df0c775d4b36f03d8e0ac25/robotframework-3.1.1-py2.py3-none-any.whl";
      sha256 = "0fgx2wygf6fj8r4lv5x5xzdfy1hzl88ib2qwc16s67aqpvc62dx4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "robotframework-selenium2library" = super.buildPythonPackage rec {
    pname = "robotframework-selenium2library";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/f1/612f9aa29f33b25a1034749dde67dfbf6de9b297709d06df71f9bfabfc81/robotframework_selenium2library-3.0.0-py2.py3-none-any.whl";
      sha256 = "1c9cwb14hmd4xqkw8n9wibdfqllzyxnjsbl1qha6ziyaik7b29hq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."robotframework-seleniumlibrary"
    ];
  };
  "robotframework-seleniumlibrary" = super.buildPythonPackage rec {
    pname = "robotframework-seleniumlibrary";
    version = "3.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/15/6961c801eeec7f062973509958b33f158bbc505d45ee6c20b2966275ef51/robotframework_seleniumlibrary-3.3.1-py2.py3-none-any.whl";
      sha256 = "0p3s3y33h1rws5np57zzdkpiihlib7qfp7d5ihv78iwf2ah9rhzl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."robotframework"
      self."selenium"
    ];
  };
  "selenium" = super.buildPythonPackage rec {
    pname = "selenium";
    version = "3.141.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl";
      sha256 = "0g6bwadmm1757n6yxcd1ihxv04f428kayjmhv6i9jnsspkbk2w9d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."urllib3"
    ];
  };
  "setuptools-git" = super.buildPythonPackage rec {
    pname = "setuptools-git";
    version = "1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/97/dd99fa9c0d9627a7b3c103a00f1566d8193aca8d473884ed258cca82b06f/setuptools_git-1.2-py2.py3-none-any.whl";
      sha256 = "1yjc97r57mfsrvb3yx45cc1aryf6m9kbkmrhlfsv95vxrv64sxp7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "setuptools-scm" = super.buildPythonPackage rec {
    pname = "setuptools-scm";
    version = "3.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/70/97966deebaeeda0b81d3cd63ba9f8ec929b838871ed17476de9d8159db3e/setuptools_scm-3.3.3-py2.py3-none-any.whl";
      sha256 = "0j61sn509ljj6x6bqw1cgcfdrrz2mzydmhl9cpa4c4s3x8pcn48z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl";
      sha256 = "073nyd09fqi2xwalmsi2lf8lrwnma85hscs84iaizcam0ngq0l1k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl";
      sha256 = "06zapfly613h9lllvra08hp8jnlcynbv4dn7pxgijjvfdlw0ycq6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "watchdog" = super.buildPythonPackage rec {
    pname = "watchdog";
    version = "0.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bb/e3/5a55d48a29300160779f0a0d2776d17c1b762a2039b36de528b093b87d5b/watchdog-0.9.0.tar.gz";
      sha256 = "07cnvvlpif7a6cg4rav39zq8fxa5pfqawchr46433pij0y6napwn";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYAML"
      self."argh"
      self."pathtools"
    ];
  };
  "wmctrl" = super.buildPythonPackage rec {
    pname = "wmctrl";
    version = "0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/c6/001aefbde5782d6f359af0a8782990c3f4e751e29518fbd59dc8dfc58b18/wmctrl-0.3.tar.gz";
      sha256 = "04wacb7lj7rbpx5q5cnb19n9k4w85szdfa8xwfv6chsmq5dgc1nq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zc.buildout" = super.buildPythonPackage rec {
    pname = "zc.buildout";
    version = "2.13.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/69/3584b5d1f197460194647aa12c627cb4b0b822ee1782fd6c867280f2e6d7/zc.buildout-2.13.4.tar.gz";
      sha256 = "0qzgzs2q4k7iaq4pzr5av8dw86jvy32gqy0z37j7wcbv67wv4y5r";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
    ];
  };
}
