[
  ./env-fonts.nix
  ./env-locale.nix
  ./env-network.nix
  ./hw-yubikey.nix
  ./programs-devenv.nix
  ./programs-discord.nix
  ./programs-agent-sandbox.nix
  ./programs-bpmn-to-image.nix
  ./programs-evince.nix
  ./programs-gimp.nix
  ./programs-git.nix
  ./programs-lock-session.nix
  ./programs-libreoffice.nix
  ./programs-minecraft.nix
  ./programs-obs.nix
  ./programs-shell.nix
  ./programs-nushell-ai.nix
  ./programs-ssh.nix
  ./programs-taskwarrior.nix
  ./programs-vim.nix
  ./programs-vscodium.nix
  ./services-battery-notifier.nix
  ./services-fineid.nix
  ./services-gammastep.nix
  ./services-virtualization.nix
  ./programs-password-managers.nix
  # ./services-email.nix # Uncomment after encrypting secrets/email.yaml with sops
]
