[
  ./env-fonts.nix
  ./env-locale.nix
  ./env-network.nix
  ./hw-yubikey.nix
  ./programs-discord.nix
  ./programs-git.nix
  ./programs-minecraft.nix
  ./programs-obs.nix
  ./programs-shell.nix
  ./programs-ssh.nix
  ./programs-vim.nix
  ./services-battery-notifier.nix
  ./services-fineid.nix
  ./services-gammastep.nix
  ./services-virtualization.nix
]
