# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/mattn/go-sqlite3";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-sqlite3";
      rev = "6c771bb9887719704b210e87e934f08be014bdb1";
      sha256 = "0x6s7hy3ab3qw6dfl81y7ighjva5j4rrzvqhppf1qwz5alpfmpdm";
    };
  }
  {
    goPackagePath = "github.com/opennota/phash";
    fetch = {
      type = "git";
      url = "https://github.com/opennota/phash";
      rev = "da2cd1016280b8acd10a0ae5e45483aff8fe44b7";
      sha256 = "0c9qpskqcq6nfccnzhya43gkpgza0dwkc6hk17z1k7ywfn2723v1";
    };
  }
  {
    goPackagePath = "github.com/rakyll/magicmime";
    fetch = {
      type = "git";
      url = "https://github.com/rakyll/magicmime";
      rev = "8698a7074799189633f3be29613cc24c4511a771";
      sha256 = "1wlii573j1ilz6mzkn26d0rdh5l8wnqaflz2pkyiigrf7i5f4mg3";
    };
  }
]
