# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "ehci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a13769b8-e575-465c-afd5-1ade83f2c435";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/9f37984d-88ba-4857-af2c-4941e2077f2b"; } ];

  # # Use the systemd-boot EFI boot loader.
  # boot.loader.systemd-boot.enable = true;
  # boot.loader.efi.canTouchEfiVariables = true;

  # Clean tmp on reboot
  boot.cleanTmpDir = true;

  # Enable scheduled TRIM for SSD
  services.fstrim.enable = true;

  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "conservative";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  services.batteryNotifier.enable = true;

  # GRUB
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.efiSupport = true;

  # services.logind.extraConfig = ''
  #   RuntimeDirectorySize=7.8G
  # '';

  networking.hostName = "shangri-la";
  networking.hosts = {
    "127.0.0.1" = [ "localhost" ];
    "127.0.1.1" = [ "shangri-la" ];
    "::1" = [ "localhost" ];
  };

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = false;
  networking.interfaces.wlp3s0.useDHCP = true;

  # Mouse
  services.xserver.inputClassSections = [
    ''
      Identifier      "Trackpoint Wheel Emulation"
      Driver          "evdev"
      MatchProduct    "TPPS/2 IBM TrackPoint"
      MatchDevicePath "/dev/input/event*"
      Option          "EmulateWheel"       "true"
      Option          "EmulateWheelButton" "2"
      Option          "Emulate3Buttons"    "false"
      Option          "XAxisMapping"       "6 7"
      Option          "YAxisMapping"       "4 5"
    ''
  ];

  # Graphics
  hardware.opengl.enable = true;

  # Bluetooth
  hardware.bluetooth.enable = false;

  # Unfree
  nixpkgs.config.allowUnfreePredicate =
    pkg:
    builtins.elem (pkgs.lib.getName pkg) [
      "Oracle_VM_VirtualBox_Extension_Pack"
      "code"
      "corefonts"
      "vscode"
      "zoom"
    ];

  # Initial system version
  system.stateVersion = "21.11";
}
