# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz";
      sha256 = "0sqipg4fk7xbixqd8kq6rlkxj664d157bdwbh93farcphf92x1r9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Send2Trash" = super.buildPythonPackage rec {
    pname = "Send2Trash";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/46/c3dc27481d1cc57b9385aff41c474ceb7714f7935b1247194adae45db714/Send2Trash-1.5.0-py3-none-any.whl";
      sha256 = "12w8x95c7nnj91wm7jmr014pr24xb5bynji344la2vvvawi1jsgi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "atomicwrites" = super.buildPythonPackage rec {
    pname = "atomicwrites";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl";
      sha256 = "1d0id3y2hbnwjfm8hf6spfzpya5qdak2qk3y4alinp9cxcq2qiq3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "19.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl";
      sha256 = "0ybaycx149w1q2fqkjv119l83vx5115l8167bv5y2b9rxprdph39";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "backcall" = super.buildPythonPackage rec {
    pname = "backcall";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz";
      sha256 = "1r01dqch3f8fdj3n6fviw8hxqrs6w5v0qw4izmvqzry1w9dxiv1q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "bleach" = super.buildPythonPackage rec {
    pname = "bleach";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl";
      sha256 = "05js50g5sny3bncfsbxzlv2spbwp0cnxsxyykinz4ahhkvj3ccr1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "4.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl";
      sha256 = "1xng99yyb5rv7g0zbmz0g5dhnjj5g0idx3r5lm5pbjih32hg6sgh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "defusedxml" = super.buildPythonPackage rec {
    pname = "defusedxml";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl";
      sha256 = "14zglgld9yp35l89dqs9ayfdsix84yrs3dqvb2mp90s3f03ib1v6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "entrypoints" = super.buildPythonPackage rec {
    pname = "entrypoints";
    version = "0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl";
      sha256 = "06bdwpdvijwfwlscrvcix9prnkiavvpxf33fpqsssf9p655qg7sq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "0.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/15/29e4fe1624373be313b5a2565d72ca9121a37f40472112f46eda8dc1235b/importlib_metadata-0.22-py2.py3-none-any.whl";
      sha256 = "0pyh8dfqpzn7m9ycg7b7wp7pd8z6ayjsjpsky30jn148zf34j9kg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "ipykernel" = super.buildPythonPackage rec {
    pname = "ipykernel";
    version = "5.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/16/43f51f65a8a08addf04f909a0938b06ba1ee1708b398a9282474531bd893/ipykernel-5.1.2-py3-none-any.whl";
      sha256 = "10s3hqlfgsm1livr72b5jgpzpq5hmh2rjx3cnxhf1xahhkq3wz0n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-client"
      self."tornado"
      self."traitlets"
    ];
  };
  "ipython" = super.buildPythonPackage rec {
    pname = "ipython";
    version = "7.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/44/f28a13852e562af719f9de1761680a84a93e8b4c50e22d00d68f60ee2e8b/ipython-7.8.0-py3-none-any.whl";
      sha256 = "16zfbmgdjksbj6v82kg1jx24dk0zg9p2hpj0isk407k445ch1ay4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."backcall"
      self."decorator"
      self."jedi"
      self."pexpect"
      self."pickleshare"
      self."prompt-toolkit"
      self."pygments"
      self."setuptools"
      self."traitlets"
    ];
  };
  "ipython-genutils" = super.buildPythonPackage rec {
    pname = "ipython-genutils";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl";
      sha256 = "1f7sc4ydjj33gadcgfz8fcx02d1wm2frlqwzdik1krlr6wikgpbj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ipywidgets" = super.buildPythonPackage rec {
    pname = "ipywidgets";
    version = "7.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/a0/dbcf5881bb2f51e8db678211907f16ea0a182b232c591a6d6f276985ca95/ipywidgets-7.5.1-py2.py3-none-any.whl";
      sha256 = "05hmfyd0w52pnzl7pb4hhfrddfbr0gsj5p43wldgkh7072jfrzqk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."nbformat"
      self."traitlets"
      self."widgetsnbextension"
    ];
  };
  "jedi" = super.buildPythonPackage rec {
    pname = "jedi";
    version = "0.15.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/54/da994f359e4e7da4776a200e76dbc85ba5fc319eefc22e33d55296d95a1d/jedi-0.15.1-py2.py3-none-any.whl";
      sha256 = "09qsq9m1scqag5m8jqjxvqns5fmqh7npz832f7bnzw72h0ynqsvq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parso"
    ];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "2.10.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl";
      sha256 = "0yqwnvqsxf74l4m5ayfv7slkp1a0mi77hv7q10gv5ar72npnrp8l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "json5" = super.buildPythonPackage rec {
    pname = "json5";
    version = "0.8.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/68/e182f2c6e8d672dbf368a06640ccfc0fb64ef181f721ec29c16d9c383f98/json5-0.8.5.tar.gz";
      sha256 = "1c3k5blbhq7g2lnbap26a846ag5x19ivisd3wfzz6bzdl46hyjqj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "3.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/48/f5f11003ceddcd4ad292d4d9b5677588e9169eef41f88e38b2888e7ec6c4/jsonschema-3.0.2-py2.py3-none-any.whl";
      sha256 = "13q63axr1jddhrm86afv762kxlfj9yk51lrgvv2i9km2kiqhm72z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."pyrsistent"
      self."setuptools"
      self."six"
    ];
  };
  "jupyter" = super.buildPythonPackage rec {
    pname = "jupyter";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/a9/371d0b8fe37dd231cf4b2cff0a9f0f25e98f3a73c3771742444be27f2944/jupyter-1.0.0.tar.gz";
      sha256 = "0pwf3pminkzyzgx5kcplvvbvwrrzd3baa7lmh96f647k30rlpp6r";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipywidgets"
      self."jupyter-console"
      self."nbconvert"
      self."notebook"
      self."qtconsole"
    ];
  };
  "jupyter-client" = super.buildPythonPackage rec {
    pname = "jupyter-client";
    version = "5.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/4c/bf613864ae0644e2ac7d4a40bd209c40c8c71e3dc88d5f1d0aa92a68e716/jupyter_client-5.3.1-py2.py3-none-any.whl";
      sha256 = "1cv50i481kq1b7f56kg8nzxjz35mvmzm688mrjnhgyjajsi0ka3k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-console" = super.buildPythonPackage rec {
    pname = "jupyter-console";
    version = "6.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/ee/6374ae8c21b7d0847f9c3722dcdfac986b8e54fa9ad9ea66e1eb6320d2b8/jupyter_console-6.0.0-py2.py3-none-any.whl";
      sha256 = "0s1mpf26zjzmdg8ys6c2x6yncjzxrvkmryrg4lqbv71qbixak06c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."jupyter-client"
      self."prompt-toolkit"
      self."pygments"
    ];
  };
  "jupyter-contrib-core" = super.buildPythonPackage rec {
    pname = "jupyter-contrib-core";
    version = "0.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/8f/04a752a8b66a66e7092c035e5d87d2502ac7ec07f9fb6059059b6c0dc272/jupyter_contrib_core-0.3.3-py2.py3-none-any.whl";
      sha256 = "03z5vly0qqhwwmznbf01a28qxaimagc6qk0cdgamhn4gb8kixj0y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-core"
      self."notebook"
      self."setuptools"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-contrib-nbextensions" = super.buildPythonPackage rec {
    pname = "jupyter-contrib-nbextensions";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/33/f0/6e2c00afda860f655fbf0f795f7310bdbf12122846344dfdc803fc7455d5/jupyter_contrib_nbextensions-0.5.1-py2.py3-none-any.whl";
      sha256 = "0h7z608b239mnrnz81lzry9s8v4hcq7xqsv5dxk6ki88l851y1rc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jupyter-contrib-core"
      self."jupyter-core"
      self."jupyter-highlight-selected-word"
      self."jupyter-latex-envs"
      self."jupyter-nbextensions-configurator"
      self."lxml"
      self."nbconvert"
      self."notebook"
      self."pyyaml"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-core" = super.buildPythonPackage rec {
    pname = "jupyter-core";
    version = "4.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/25/6ffb0f6e57fa6ef5d2f814377133b361b42a6dd39105f4885a4f1666c2c3/jupyter_core-4.5.0-py2.py3-none-any.whl";
      sha256 = "114bipndb6z5zg5pnm821z3padb94cljvwlmr43liwr5rzb25ypl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."traitlets"
    ];
  };
  "jupyter-highlight-selected-word" = super.buildPythonPackage rec {
    pname = "jupyter-highlight-selected-word";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/50/d7/19ab7cfd60bf268d2abbacc52d4295a40f52d74dfc0d938e4761ee5e598b/jupyter_highlight_selected_word-0.2.0-py2.py3-none-any.whl";
      sha256 = "0n1wj2sw2rqb3bv57r9phshlwad5sgf08mkrlpiynzh5rflxyicm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jupyter-latex-envs" = super.buildPythonPackage rec {
    pname = "jupyter-latex-envs";
    version = "1.4.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/15/55805de080d5542f76920364635e96e64d3b37f678befdfe3b16aa154205/jupyter_latex_envs-1.4.6.tar.gz";
      sha256 = "0wiq6jssjdnvicwrnrivbjzlg4lkqakpjn4ihflvp2645pmk22h7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-core"
      self."nbconvert"
      self."notebook"
      self."traitlets"
    ];
  };
  "jupyter-nbextensions-configurator" = super.buildPythonPackage rec {
    pname = "jupyter-nbextensions-configurator";
    version = "0.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/a3/d72d5f2dc10c5ccf5a6f4c79f636bf071a5ce462dedd07af2f70384db6cb/jupyter_nbextensions_configurator-0.4.1.tar.gz";
      sha256 = "10sfdq3rkffpc8rgzwzyk3vrjsb9v158xc7b63xiz3l9kmfnps75";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-contrib-core"
      self."jupyter-core"
      self."notebook"
      self."pyyaml"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyterlab" = super.buildPythonPackage rec {
    pname = "jupyterlab";
    version = "1.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/12/c9d245eb44e11e3a3871390fa8e4d97395b002abd248d4d21ecdfd070abc/jupyterlab-1.1.3-py2.py3-none-any.whl";
      sha256 = "0nb8v5az7ymr8rj9sn3manvd8nqp9906wr2h1f96vahd4whfdvmy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."jupyterlab-server"
      self."notebook"
      self."tornado"
    ];
  };
  "jupyterlab-server" = super.buildPythonPackage rec {
    pname = "jupyterlab-server";
    version = "1.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/98/5b87b9d38176bd98f23b58a8fb730e5124618d68571a011abbd38ad4a842/jupyterlab_server-1.0.6-py3-none-any.whl";
      sha256 = "0is46sam95w8f205z3l008f6fcxql7lc3l7qsa7qvbgpjzqbrhyr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."json5"
      self."jsonschema"
      self."notebook"
    ];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/43/3f1e7d742e2a7925be180b6af5e0f67d38de2f37560365ac1a0b9a04c015/lxml-4.4.1.tar.gz";
      sha256 = "14jnpfcpgqr9sx8ppd286jzcbk0b36hbqsvd8jkvffipzw5v8768";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mistune" = super.buildPythonPackage rec {
    pname = "mistune";
    version = "0.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl";
      sha256 = "1m5qdckapi46npn36jqljlj2dqgzdm3qslz8xs4a5381fcc0b8c8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "more-itertools" = super.buildPythonPackage rec {
    pname = "more-itertools";
    version = "7.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl";
      sha256 = "1i30pck2xhfxqy4z0j5bq6xf3cjjvqp2z6vjq08hckxcdnqc9f4j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nbconvert" = super.buildPythonPackage rec {
    pname = "nbconvert";
    version = "5.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/df/4505c0a7fea624cac461d0f41051f33456ae656753f65cee8c2f43121cb2/nbconvert-5.6.0-py2.py3-none-any.whl";
      sha256 = "02977crnfyflddh1b3rbqxgz5fbsyagx887qilgg4b3s0m1c7ls8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."bleach"
      self."defusedxml"
      self."entrypoints"
      self."jinja2"
      self."jupyter-core"
      self."mistune"
      self."nbformat"
      self."pandocfilters"
      self."pygments"
      self."testpath"
      self."traitlets"
    ];
  };
  "nbformat" = super.buildPythonPackage rec {
    pname = "nbformat";
    version = "4.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl";
      sha256 = "02rvfiakjpf55lzshjv7q740isjjyvbayg49z3s39c2vskdxp85r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jsonschema"
      self."jupyter-core"
      self."traitlets"
    ];
  };
  "nbimporter" = super.buildPythonPackage rec {
    pname = "nbimporter";
    version = "0.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/a1/9771984f60c4ea6d0c36215b44a5c1537cfda845c08e7ee5cf748c43d7cf/nbimporter-0.3.1.tar.gz";
      sha256 = "1kvjpyjaa9qj9qw4n4q1q49g8zdk2d462ah27cwx8sd17prvmmzi";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "notebook" = super.buildPythonPackage rec {
    pname = "notebook";
    version = "6.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/a1/1e07cedcb554408fefe4a7d32b2a041c86517167aec6ca8251c808ef6c1e/notebook-6.0.1-py3-none-any.whl";
      sha256 = "086y9csvbi7fkb71dagg02zj1n0x48y2pimy445db4kprksr18mh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Send2Trash"
      self."ipykernel"
      self."ipython-genutils"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."nbconvert"
      self."nbformat"
      self."prometheus-client"
      self."pyzmq"
      self."terminado"
      self."tornado"
      self."traitlets"
    ];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "19.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/22/630ac83e8f8a9566c4f88038447ed9e16e6f10582767a01f31c769d9a71e/packaging-19.1-py2.py3-none-any.whl";
      sha256 = "1ycca9ak1mfpabc63vdhqgn79lnc6m2gwn401bl7xh7xjxxqdb57";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."pyparsing"
      self."six"
    ];
  };
  "pandocfilters" = super.buildPythonPackage rec {
    pname = "pandocfilters";
    version = "1.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/ea/236e2584af67bb6df960832731a6e5325fd4441de001767da328c33368ce/pandocfilters-1.4.2.tar.gz";
      sha256 = "1a8d9b7s48gmq9zj0pmbyv2sivn5i7m6mybgpkk4jm5vd7hp1pdk";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "parso" = super.buildPythonPackage rec {
    pname = "parso";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/bd/bf4e5bd01d79906e5b945a7af033154da49fd2b0d5b5c705a21330323305/parso-0.5.1-py2.py3-none-any.whl";
      sha256 = "1p4p4wij05pckcwpwplnhl5pblj68frbci17gylmvnzsw4rl51b3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pexpect" = super.buildPythonPackage rec {
    pname = "pexpect";
    version = "4.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl";
      sha256 = "1lawiraiqlfvic4fgrz0qzjphj0s5j39184szgdiyypkzkyyx510";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
  };
  "pickleshare" = super.buildPythonPackage rec {
    pname = "pickleshare";
    version = "0.7.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl";
      sha256 = "0mnzcb714ynl1qlv9dwnh50rv75mmj18ywaxbl8xzm3l9m0syjcn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "0.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/c7/48439f7d5fd6bddb4c04b850bb862b42e3e2b98570040dfaf68aedd8114b/pluggy-0.13.0-py2.py3-none-any.whl";
      sha256 = "1rn39rg4ncng4m5rdrn1hn8s2nl4fsj2sa1kl2s3a7df39hbgd0d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
  };
  "prometheus-client" = super.buildPythonPackage rec {
    pname = "prometheus-client";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/23/41a5a24b502d35a4ad50a5bb7202a5e1d9a0364d0c12f56db3dbf7aca76d/prometheus_client-0.7.1.tar.gz";
      sha256 = "1ni2yv4ixwz32nz39ckia76lvggi7m19y5f702w5qczbnfi29kbi";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "2.0.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f7/a7/9b1dd14ef45345f186ef69d175bdd2491c40ab1dfa4b2b3e4352df719ed7/prompt_toolkit-2.0.9-py3-none-any.whl";
      sha256 = "101p8qhz3ri83g3rw30x53ymm2iysp880x97ri2nsslrk8wg7b8i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
  };
  "ptyprocess" = super.buildPythonPackage rec {
    pname = "ptyprocess";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl";
      sha256 = "07yaymg8cpnh675miwk62gf20d33sddk6h567i144qz7fs6m5k6p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "py" = super.buildPythonPackage rec {
    pname = "py";
    version = "1.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl";
      sha256 = "1ylkczijmfk6vrv8dj4sdfdmpwf38yhs6rkplb783cz5mramgxk4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl";
      sha256 = "09q1bggw7yxwx2ayqskg3ml7yh6j66rxkh8a007l72n8hny31r3i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "2.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl";
      sha256 = "1d18n2lq47808yxm55j85q6v2s0r2v18fkhfbbbgbfq357qqscyr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrsistent" = super.buildPythonPackage rec {
    pname = "pyrsistent";
    version = "0.15.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/66/b2638d96a2d128b168d0dba60fdc77b7800a9b4a5340cefcc5fc4eae6295/pyrsistent-0.15.4.tar.gz";
      sha256 = "0cv5xvhfhlj88pb0ghdwivkfcmgi6503qjwxx4r6n06nd6hpzd1l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [
      self."pytest"
    ];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "4.6.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/72/d4d6d22ad216f149685f2e93ce9280df9f36cbbc87fa546641ac92f22766/pytest-4.6.5-py2.py3-none-any.whl";
      sha256 = "1w0lk3ri39g05fa4rwqmdpp7z199vc185w73yzfgargnf0ks006i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."atomicwrites"
      self."attrs"
      self."importlib-metadata"
      self."more-itertools"
      self."packaging"
      self."pluggy"
      self."py"
      self."six"
      self."wcwidth"
    ];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl";
      sha256 = "1yzj7m4h5babisvqac674xx82a8gd7ynxqhm2rwj7mpf9b3q8rby";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "5.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz";
      sha256 = "1r5faspz73477hlbjgilw05xsms0glmsa371yqdd26znqsvg1b81";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyzmq" = super.buildPythonPackage rec {
    pname = "pyzmq";
    version = "18.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/d2/1eb3a994374802b352d4911f3317313a5b4ea786bc830cc5e343dad9b06d/pyzmq-18.1.0.tar.gz";
      sha256 = "1cxybx8j9zr8s1vv7f54ylyaz80svd1hx68n780lq8v9vcwlgx4k";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "qtconsole" = super.buildPythonPackage rec {
    pname = "qtconsole";
    version = "4.5.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/fc/4936c60be8d56acedfefcc13cf9f3d881e4036147d78e86160463c92d1b7/qtconsole-4.5.5-py2.py3-none-any.whl";
      sha256 = "00rpjazxxn7zqcrq5kb7in5pnndrqisdmw7nvdka43h71phdima0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython-genutils"
      self."jupyter-client"
      self."jupyter-core"
      self."pygments"
      self."traitlets"
    ];
  };
  "rise" = super.buildPythonPackage rec {
    pname = "rise";
    version = "5.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/e2/231c7433cc13a147d32ed4e359fac633400604cce0c51742d163d222e0ae/rise-5.5.1-py2.py3-none-any.whl";
      sha256 = "1qr9qsmm51p9n7yg0xh503vczbv4h1lbh3bwckqb4g4rxqd3555s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."notebook"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl";
      sha256 = "073nyd09fqi2xwalmsi2lf8lrwnma85hscs84iaizcam0ngq0l1k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "terminado" = super.buildPythonPackage rec {
    pname = "terminado";
    version = "0.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a7/56/80ea7fa66565fa75ae21ce0c16bc90067530e5d15e48854afcc86585a391/terminado-0.8.2-py2.py3-none-any.whl";
      sha256 = "0q7l3v84bcr9whgflflgsb7jyz1k8cq7rhb9r4x25f5ccgg15l6r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
      self."tornado"
    ];
  };
  "testpath" = super.buildPythonPackage rec {
    pname = "testpath";
    version = "0.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/a4/162f9ebb6489421fe46dcca2ae420369edfee4b563c668d93cb4605d12ba/testpath-0.4.2-py2.py3-none-any.whl";
      sha256 = "0281gcqv5ikrbmvb6g4a61wd1m414pqxj3mb5bz3yirzd2xrxj26";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tornado" = super.buildPythonPackage rec {
    pname = "tornado";
    version = "6.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887fcef78b6eade136b/tornado-6.0.3.tar.gz";
      sha256 = "1afpxpv75zi1zvj2b3s6d7r4s4p0z2byh7jv9h3i4sb1p8vdnif8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "traitlets" = super.buildPythonPackage rec {
    pname = "traitlets";
    version = "4.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl";
      sha256 = "1nf72xiap5frnlariklymgxrh0pk99xwwwgs82mbvaf5axpmxjy6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."ipython-genutils"
      self."six"
    ];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl";
      sha256 = "0z6yi9wgxisnsz14c5zpz123bd2rslg7cgsmcjl40yxg4lcygszl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "webencodings" = super.buildPythonPackage rec {
    pname = "webencodings";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl";
      sha256 = "0y2aa53jkkcszhbbx59z817ywjvy3ah3lavym6bn88n2yc9i5bx0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "widgetsnbextension" = super.buildPythonPackage rec {
    pname = "widgetsnbextension";
    version = "3.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/7b/7ac231c20d2d33c445eaacf8a433f4e22c60677eb9776c7c5262d7ddee2d/widgetsnbextension-3.5.1-py2.py3-none-any.whl";
      sha256 = "1kcbjd8rfj1sp63277caz3d0mfkczjwwav7azyjp31a8xf64ycdx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."notebook"
    ];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl";
      sha256 = "0d9kggxfnvdf51ljciy7mm29mcvan33lljq0f79i4fzly7lh6sgh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."more-itertools"
    ];
  };
}
