# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Pygments" = super.buildPythonPackage {
    name = "Pygments-2.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/2a/2e4e77803a8bd6408a2903340ac498cb0a2181811af7c9ec92cb70b0308a/Pygments-2.2.0.tar.gz";
      sha256 = "1k78qdvir1yb1c634nkv6rbga8wv4289xarghmsbbvzhvr311bnv";
    };
  };
  "bleach" = super.buildPythonPackage {
    name = "bleach-3.0.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/31/680afc7d44040004296a2d8f0584983c2f2386448cd9d0964197e6c1160e/bleach-3.0.2.tar.gz";
      sha256 = "06474zg7f73hv8h1xw2wcsmvn2ygj73zxgxxqg8zcx8ap1srdls8";
    };
  };
  "certifi" = super.buildPythonPackage {
    name = "certifi-2018.10.15";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/b6/4f0cefba47656583217acd6cd797bc2db1fede0d53090fdc28ad2c8e0716/certifi-2018.10.15.tar.gz";
      sha256 = "0slqq22vgh7lcvkq6dawl1rd3rm34fgn63gk1n68q0rbsa3cjn3d";
    };
  };
  "cffi" = super.buildPythonPackage {
    name = "cffi-1.11.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."pycparser"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz";
      sha256 = "1x3lrj928dcxx1k8k9gf3s4s3jwvzv8mc3kkyg1g7c3a1sc1f3z9";
    };
  };
  "chardet" = super.buildPythonPackage {
    name = "chardet-3.0.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  "check-manifest" = super.buildPythonPackage {
    name = "check-manifest-0.37";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/ac/67d065556adcad8144cb51e9d8848006dc3a9f5da7491faaf7db6374e301/check-manifest-0.37.tar.gz";
      sha256 = "0lk45ifdv2cpkl6ayfyix7jwmnxa1rha7xvb0ih5999k115wzqs4";
    };
  };
  "cmarkgfm" = super.buildPythonPackage {
    name = "cmarkgfm-0.4.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."cffi"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e2/a3/4021fbc17c5afe7f307d14eba0d6899a8e66b351ab65649b1c89c50a836d/cmarkgfm-0.4.2.tar.gz";
      sha256 = "0350y5z5qggp7lyiqn9rhj0301f89g9li4xfhfbi1wkpcgqh02gj";
    };
  };
  "colorama" = super.buildPythonPackage {
    name = "colorama-0.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/d5/c35bd3e63757ac767105f8695b055581d8b8dd8c22fef020ebefa2a3725d/colorama-0.4.0.zip";
      sha256 = "0p2rhr04426bmgxl3lbwn7z6p4pjacfmdj3j0wz80shsx7mlpdf9";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  "future" = super.buildPythonPackage {
    name = "future-0.16.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz";
      sha256 = "1nzy1k4m9966sikp0qka7lirh8sqrsyainyf8rk97db7nwdfv773";
    };
  };
  "gocept.zestreleaser.customupload" = super.buildPythonPackage {
    name = "gocept.zestreleaser.customupload-3.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."setuptools"
      self."six"
      self."zest.releaser"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/6a/b2c181d572df6027271531f4d17e9bea9452130d9a8b2cb64f3e91339072/gocept.zestreleaser.customupload-3.0.tar.gz";
      sha256 = "157iifvcqm60x9yjvyg4krqn7s6jphn8mym69f24l37m44zkwb64";
    };
  };
  "idna" = super.buildPythonPackage {
    name = "idna-2.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/c4/80f97e9c9628f3cac9b98bfca0402ede54e0563b56482e3e6e45c43c4935/idna-2.7.tar.gz";
      sha256 = "05jam7d31767dr12x0rbvvs8lxnpb1mhdb2zdlfxgh83z6k3hjk8";
    };
  };
  "pkginfo" = super.buildPythonPackage {
    name = "pkginfo-1.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/c9/111ececbeed8e69cd1b6bec79a32a0b0f6074038a4244e58e285ad278248/pkginfo-1.4.2.tar.gz";
      sha256 = "0x6lm17p1ks031mj6pajyp4rkq74vpqq8qwjb7ikgwmkli1day2q";
    };
  };
  "pycparser" = super.buildPythonPackage {
    name = "pycparser-2.19";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz";
      sha256 = "1cr5dcj9628lkz1qlwq3fv97c25363qppkmcayqvd05dpy573259";
    };
  };
  "pyroma" = super.buildPythonPackage {
    name = "pyroma-2.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/de/f3/104ae27624982cd4b6de786d9afe23a2dc0b8c0999443ba370b3755848c7/pyroma-2.2.tar.gz";
      sha256 = "0l5ab84plqf6gy2xphm92dazpa6c5r1xcj20f35zhlbwd1aq1zfk";
    };
  };
  "python-gettext" = super.buildPythonPackage {
    name = "python-gettext-3.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/a7/a4a5cf3aa9500dbb09b48dae6d4d9581883dd90ae7a84cbb2d3448410114/python-gettext-3.0.zip";
      sha256 = "0mil2vbv27i3ij8k0n31n39j2h3sxh589bvsvwrhwq6w9qr401gl";
    };
  };
  "readme-renderer" = super.buildPythonPackage {
    name = "readme-renderer-22.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."Pygments"
      self."bleach"
      self."cmarkgfm"
      self."docutils"
      self."future"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/aa/b6/384c1dfe9b3ac3404817ac32fa44abbe0b51c2494ba118e0ad7ff3e72efb/readme_renderer-22.0.tar.gz";
      sha256 = "1lj3k3x7wm0w5xdy82jwl0fmchqmlkdh24g41n3lka7ybxqahz13";
    };
  };
  "requests" = super.buildPythonPackage {
    name = "requests-2.20.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/10/92d25b93e9c266c94b76a5548f020f3f1dd0eb40649cb1993532c0af8f4c/requests-2.20.0.tar.gz";
      sha256 = "033p8ax4qs81g0c95ngincm52q84g1xnlazk4vjzdjhpxfmgvp4r";
    };
  };
  "requests-toolbelt" = super.buildPythonPackage {
    name = "requests-toolbelt-0.8.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/86/f9/e80fa23edca6c554f1994040064760c12b51daff54b55f9e379e899cd3d4/requests-toolbelt-0.8.0.tar.gz";
      sha256 = "1dc7l42i4080r8i4m9fj51jx367lqkai170vrv7wd93gdj9k39gn";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-40.4.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/9c/6a003320b00ef237f94aa74e4ad66c57a7618f6c79d67527136e2544b728/setuptools-40.4.3.zip";
      sha256 = "058v6zns4634n4al2nmmvp15j8nrgwn8wjrbdks47wk3vm05gg5c";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.11.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz";
      sha256 = "1scqzwc51c875z23phj48gircqjgnn3af8zy2izjwmnlxrxsgs3h";
    };
  };
  "tqdm" = super.buildPythonPackage {
    name = "tqdm-4.27.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/2e/f1ce746f1e8eddee065b0ab55bb57f00c493c9d626b6d0396e0093db9a2e/tqdm-4.27.0.tar.gz";
      sha256 = "0bkvksrf2rfr25x7673gfhgr4iqdi7860nwsf3zj04hn26amdgm0";
    };
  };
  "twine" = super.buildPythonPackage {
    name = "twine-1.12.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."pkginfo"
      self."readme-renderer"
      self."requests"
      self."requests-toolbelt"
      self."setuptools"
      self."tqdm"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/29/4d/801bbad5968e674c1ca047118025243a475f986a6f5b3ca36e5afece0f9f/twine-1.12.1.tar.gz";
      sha256 = "0p3wh8sq61af9hm0r5lqy05h6xxc4vprbcp5wqjd2cgvr9mbr2bx";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.24";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/74/05ffd00b4b5c08306939c485869f5dc40cbc27357195b0a98b18e4c48893/urllib3-1.24.tar.gz";
      sha256 = "1bk54bm9zxa9d2snwklrsqvlx9yhz5rfq381i1r90nqyq0pxphs1";
    };
  };
  "webencodings" = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  "wheel" = super.buildPythonPackage {
    name = "wheel-0.32.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e2/d0/bb5eedd650e777039d984b209d229b97fa2161916c920245a85c1ef07667/wheel-0.32.1.tar.gz";
      sha256 = "03ja0biv3631h6i2nkc3n3bd6p36490jpfh07hd8b88v199g85fj";
    };
  };
  "zest.pocompile" = super.buildPythonPackage {
    name = "zest.pocompile-1.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."python-gettext"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/42/6189f119fa6776c7725da9fbc767886f38ace040297d559785640591f9ad/zest.pocompile-1.4.zip";
      sha256 = "1krha8srg91clp2schxj0i2hyc11j07bxqbybcjzblp0nsv0ivsz";
    };
  };
  "zest.releaser" = super.buildPythonPackage {
    name = "zest.releaser-6.15.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."chardet"
      self."check-manifest"
      self."colorama"
      self."pyroma"
      self."readme-renderer"
      self."requests"
      self."setuptools"
      self."six"
      self."twine"
      self."wheel"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/d5/e5e45d6c50e363d66ab1588c91998d002573d58774fec44cc84d6e6fd581/zest.releaser-6.15.2.tar.gz";
      sha256 = "1yxriv97k830xbz763vnxfzsqajd4yxayrkxv2sickp9v74gbch8";
    };
  };
}
