{
  config,
  pkgs,
  lib,
  ...
}:
{
  # Session tools (brightnessctl, cbatticon, pasystray, xmousepasteblock)
  # are provided per-user by modules/home/services-xmonad.nix so that
  # standalone Home Manager hosts get the same session.
  environment.systemPackages = [
    pkgs.blueman
    pkgs.adwaita-icon-theme
    pkgs.nautilus
    pkgs.sushi
    pkgs.networkmanagerapplet
    pkgs.paprefs
    pkgs.pavucontrol
    pkgs.qpaeq
    pkgs.xlockmore
  ];
  programs.dconf.enable = true;
  services = {
    blueman.enable = true;
    dbus.packages = [ pkgs.sushi ];
    displayManager.defaultSession = "none+xmonad";
    gnome.at-spi2-core.enable = true;
    gvfs.enable = true;
    udev.packages = [ pkgs.gnome-settings-daemon ];
    xserver = {
      displayManager = {
        lightdm = {
          enable = true;
          greeters.mini = {
            enable = true;
            user = config.user.name;
          };
        };
        # Only system-level setup belongs here. The user session itself
        # (xmonad, tray applets, screen locker, ...) is managed by Home
        # Manager: the "none+xmonad" session registered below executes the
        # ~/.xsession generated by modules/home/services-xmonad.nix.
        sessionCommands =
          let
            mimeAppsList = pkgs.writeTextFile {
              name = "gnome-mimeapps";
              destination = "/share/applications/mimeapps.list";
              text = ''
                [Default Applications]
                inode/directory=nautilus.desktop;org.gnome.Nautilus.desktop
              '';
            };
          in
          ''
            # Nautilus
            export XDG_DATA_DIRS=$XDG_DATA_DIRS''${XDG_DATA_DIRS:+:}${mimeAppsList}/share
            export NAUTILUS_EXTENSION_DIR=${config.system.path}/lib/nautilus/extensions-3.0/
            ${pkgs.xdg-user-dirs}/bin/xdg-user-dirs-update
          '';
      };
      enableTCP = false;
      enable = true;
      updateDbusEnvironment = true;
      # Registers the "none+xmonad" session for the display manager. The
      # xmonad binary actually run comes from Home Manager (see above).
      windowManager.xmonad.enable = true;
      xkb.options = "eurosign:e,caps:escape,nbsp:none";
    };
  };
}
